### ISSUE TITLE
import issue 

### ISSUE THREAD

**Issue by erogol** [Blosc/bloscpack#59] opened 2017-06-12 13:00 UTC
When I import bloscpack on Ubuntu 16.04 I got 
```
Traceback (most recent call last):
  File "deneme.py", line 1, in <module>
    import bloscpack
  File "/home/egolge/miniconda3/lib/python3.6/site-packages/bloscpack/__init__.py", line 9, in <module>
    from .args import (BloscArgs,
  File "/home/egolge/miniconda3/lib/python3.6/site-packages/bloscpack/args.py", line 6, in <module>
    import blosc
  File "/home/egolge/miniconda3/lib/python3.6/site-packages/blosc/__init__.py", line 13, in <module>
    from blosc.blosc_extension import (
ImportError: /home/egolge/miniconda3/lib/python3.6/site-packages/blosc/blosc_extension.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm


```

**Comment by esc** [comment] 2017-06-12 20:08
I'm not sure what to make of this. It looks like a linking error, perhaps. It's definitely, related to the `blosc` package. Maybe you could open an issue over there so the maintainers can look at it.

**Comment by esc** [comment] 2017-06-12 20:08
Also: I am unable to reproduce this.

**Comment by esc** [comment] 2018-03-09 21:03
Closing because unable to reproduce.

**Closed** 2018-03-09 21:06 UTC
